name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests before install pahcer
        run: bun test ./test/install.test.ts

      - name: Install pahcer and set env var
        run: |
          cargo install pahcer
          echo "INSTALLED_PAHCER=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test
